<?xml version = "1.0" encoding = "UTF-8"?>
<?xml-stylesheet type="text/css" href="cd_catelog.css"?>

<!DOCTYPE CATALOG [
<!ELEMENT CATALOG (CD+)>
<!ELEMENT  CD (TITLE,ARTIST,COUNTRY,COMPANY,PRICE,YEAR)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT ARTIST (#PCDATA)>
<!ELEMENT COUNTRY (#PCDATA)>
<!ELEMENT COMPANY (#PCDATA)>
<!ELEMENT PRICE (#PCDATA)>
<!ELEMENT YEAR (#PCDATA)>
]>

<CATALOG>
  <CD>|
  <TITLE>Empire Burlesque</TITLE>
  <ARTIST>Bob Dylan</ARTIST>
  <COUNTRY>USA</COUNTRY>
  <COMPANY>Columbia</COMPANY>
  <PRICE>10.98<PRICE/>
  <YEAR>1985</YEAR>
  </CD>

  <CD>|
  <TITLE>Hide your heart</TITLE>
  <ARTIST>Bob Dylan</ARTIST>
  <COUNTRY>USA</COUNTRY>
  <COMPANY>Columbia</COMPANY>
  <PRICE>10.98<PRICE/>
  <YEAR>1985</YEAR>
  </CD>

  <CD>|
  <TITLE>Empire Burlesque</TITLE>
  <ARTIST>Bob Dylan</ARTIST>
  <COUNTRY>USA</COUNTRY>
  <COMPANY>Columbia</COMPANY>
  <PRICE>10.98<PRICE/>
  <YEAR>1985</YEAR>
  </CD>
  </CATALOG>
